name: firebase_flutter_repository
description: A reactive version of the todos repository for Flutter

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  todos_repository_core:
    path: ../todos_repository_core
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  test:
  mockito:
  flutter_test:
    sdk: flutter

flutter:
